# Generated by Django 2.2 on 2022-03-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_api', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='rating',
        ),
    ]
